// <auto-generated />
using System;
using IMS.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMS.Migrations
{
    [DbContext(typeof(IMSDBContext))]
    [Migration("20220903083914_UpdatedModel-03092022-2")]
    partial class UpdatedModel030920222
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IMS.Models.Data.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttendanceID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("AttendanceDate");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("CheckInTime");

                    b.Property<DateTime>("CheckOutTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("CheckOutTime");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternID")
                        .HasColumnType("int")
                        .HasColumnName("Intern");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceID");

                    b.ToTable("tblAttendance");
                });

            modelBuilder.Entity("IMS.Models.Data.AttendanceCorrectionRequest", b =>
                {
                    b.Property<int>("AttCorrectionReqID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttCorrectionID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("ApprovedStatus")
                        .HasColumnType("bit")
                        .HasColumnName("ApprovedStatus");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime")
                        .HasColumnName("AttendanceDate");

                    b.Property<int>("AttendanceID")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceID");

                    b.Property<string>("AttendanceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AttendanceType");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NewAttendanceTime")
                        .HasColumnType("datetime")
                        .HasColumnName("NewAttendanceTime");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Reason");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttCorrectionReqID");

                    b.ToTable("tblAttendanceCorrectionRequest");
                });

            modelBuilder.Entity("IMS.Models.Data.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentBuilding")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DepartmentBuilding");

                    b.Property<string>("DepartmentExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DepartmentExtension");

                    b.Property<string>("DepartmentFloor")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DepartmentFloor");

                    b.Property<string>("DepartmentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DepartmentLocation");

                    b.Property<string>("DepartmentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DepartmentTitle");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("User");

                    b.ToTable("tblDepartment");
                });

            modelBuilder.Entity("IMS.Models.Data.InternDetails", b =>
                {
                    b.Property<int>("InternID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InternID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNICNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CasualLeavesRemaining")
                        .HasColumnType("int")
                        .HasColumnName("CasualLeavesRemaining");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HRRepID")
                        .HasColumnType("int")
                        .HasColumnName("HRRepresentative");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastWorkingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PositionTitle");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int")
                        .HasColumnName("Program");

                    b.Property<int>("SickLeavesRemaining")
                        .HasColumnType("int")
                        .HasColumnName("SickLeavesRemaining");

                    b.Property<decimal>("Stipend")
                        .HasColumnType("money")
                        .HasColumnName("Stipend");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("InternID");

                    b.HasIndex("UserID");

                    b.ToTable("tblIntern");
                });

            modelBuilder.Entity("IMS.Models.Data.InternTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("AssignedDate");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("CompletedDate");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intern")
                        .HasColumnType("int");

                    b.Property<string>("InternRemarks")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("InternRemarks");

                    b.Property<string>("ManagerFeedback")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("ManagerFeedback");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("StartDate");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TaskDescription");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskID");

                    b.HasIndex("Intern");

                    b.ToTable("tblTask");
                });

            modelBuilder.Entity("IMS.Models.Data.InternshipProgram", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgramID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CasualLeavesAllowed")
                        .HasColumnType("int")
                        .HasColumnName("CasualLeavesAllowed");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int")
                        .HasColumnName("Department");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Duration");

                    b.Property<bool>("Open")
                        .HasColumnType("bit")
                        .HasColumnName("Open");

                    b.Property<string>("ProgramTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProgramTitle");

                    b.Property<int>("SickLeavesAllowed")
                        .HasColumnType("int")
                        .HasColumnName("SickLeavesAllowed");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("TransportAllowance");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProgramID");

                    b.ToTable("tblProgram");
                });

            modelBuilder.Entity("IMS.Models.Data.Leave", b =>
                {
                    b.Property<int>("LeaveRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LeaveRequestID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("ApprovedStatus")
                        .HasColumnType("bit")
                        .HasColumnName("ApprovedStatus");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternID")
                        .HasColumnType("int")
                        .HasColumnName("Intern");

                    b.Property<DateTime>("LeaveEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LeaveEndDate");

                    b.Property<DateTime>("LeaveStartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LeaveStartDate");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LeaveType");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Reason");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveRequestID");

                    b.ToTable("tblLeaveRequest");
                });

            modelBuilder.Entity("IMS.Models.Data.PerformanceReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternID")
                        .HasColumnType("int")
                        .HasColumnName("Intern");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Remarks");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewID");

                    b.ToTable("tblPerformanceReview");
                });

            modelBuilder.Entity("IMS.Models.Data.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FirstName");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("LastLogin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserRoleID")
                        .HasColumnType("int")
                        .HasColumnName("UserRole");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Username");

                    b.HasKey("UserID");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("IMS.Models.Data.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserRoleID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Role");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserRoleID");

                    b.ToTable("tblUserRole");
                });

            modelBuilder.Entity("IMS.Models.Data.Department", b =>
                {
                    b.HasOne("IMS.Models.Data.User", "Manager")
                        .WithMany()
                        .HasForeignKey("User");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IMS.Models.Data.InternDetails", b =>
                {
                    b.HasOne("IMS.Models.Data.User", "HRRepresentative")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HRRepresentative");
                });

            modelBuilder.Entity("IMS.Models.Data.InternTask", b =>
                {
                    b.HasOne("IMS.Models.Data.InternDetails", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("Intern")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");
                });
#pragma warning restore 612, 618
        }
    }
}
